dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U .
  - pip install -U -r test-requirements.txt

script:
  - pytest pydiff
  - pytest pydiff --pep8
