language: python

python:
  - "2.7"
  - "3.6"

install:
  - python setup.py install
  - pip install -r test-requirements.txt

script:
  - pytest pydiff
  - pytest pydiff --pep8

notifications:
  slack:
    rooms:
      - beagleinc:DB8ZeLgjLqjW9Mhn3WmXpbuW#circleci
      - serf-beagle:StH5vRHmpWcpZ6ryDdPzIkc2#ci
  email: false
