language: python

install: python setup.py install

script: pytest

notifications:
  slack:
    rooms:
      - beagleinc:DB8ZeLgjLqjW9Mhn3WmXpbuW#circleci
      - serf-beagle:StH5vRHmpWcpZ6ryDdPzIkc2#ci
