language: python

install:
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - pytest pydiff
  - pytest pydiff --pep8

notifications:
  slack:
    rooms:
      - beagleinc:DB8ZeLgjLqjW9Mhn3WmXpbuW#circleci
      - serf-beagle:StH5vRHmpWcpZ6ryDdPzIkc2#ci
  email: false
